 //
//  Problem2.swift
//  ProjectEuler
//
//  Created by Felix Ayala on 8/30/16.
//  Copyright © 2016 Felix Ayala. All rights reserved.
//

import Foundation

/**
	Problem 2: Even Fibonacci numbers

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
class Problem2: EulerProblem {
	
	let number: Int = 2
	
	func run() -> Int {
		var start = 0
		var next = 1
		var sum = 0
		
		while next < 4000000 {
			let aux = start + next
			start = next
			next = aux
			
			if next % 2 == 0 {
				sum += next
			}
		}
		
		return sum
	}
	
}
